//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskInsider
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientProfileModule
    {
        public int ClientProfileModuleID { get; set; }
        public int ClientProfileID { get; set; }
        public int ClientPhotoID { get; set; }
        public int ClientHeaderPhotoID { get; set; }
    
        public virtual ClientHeaderPhoto ClientHeaderPhoto { get; set; }
        public virtual ClientPhoto ClientPhoto { get; set; }
        public virtual ClientProfile ClientProfile { get; set; }
    }
}
