//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskInsider
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsiderProfileModule
    {
        public int InsiderProfileModuleID { get; set; }
        public int InsiderProfileID { get; set; }
        public int InsiderPhotoID { get; set; }
        public int InsiderHeaderPhotoID { get; set; }
        public int InsiderSkillID { get; set; }
    
        public virtual InsiderHeaderPhoto InsiderHeaderPhoto { get; set; }
        public virtual InsiderPhoto InsiderPhoto { get; set; }
        public virtual InsiderProfile InsiderProfile { get; set; }
        public virtual InsiderSkill InsiderSkill { get; set; }
    }
}
