//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskInsider
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsiderHeaderPhoto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InsiderHeaderPhoto()
        {
            this.InsiderProfileModules = new HashSet<InsiderProfileModule>();
        }
    
        public int InsiderHeaderPhotoID { get; set; }
        public int InsiderID { get; set; }
        public string HeaderFileName { get; set; }
    
        public virtual Insider Insider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsiderProfileModule> InsiderProfileModules { get; set; }
    }
}
