//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskInsider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public int ClientPaymentMethodID { get; set; }
        public int ServiceRequestID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal PaymentAmount { get; set; }
        public string TermsOfService { get; set; }
    
        public virtual ClientPaymentMethod ClientPaymentMethod { get; set; }
        public virtual ServiceRequest ServiceRequest { get; set; }
    }
}
