//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskInsider
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskInsiderEntities : DbContext
    {
        public TaskInsiderEntities()
            : base("name=TaskInsiderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AddressType> AddressTypes { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientAddress> ClientAddresses { get; set; }
        public virtual DbSet<ClientHeaderPhoto> ClientHeaderPhotoes { get; set; }
        public virtual DbSet<ClientPaymentMethod> ClientPaymentMethods { get; set; }
        public virtual DbSet<ClientPaymentStatu> ClientPaymentStatus { get; set; }
        public virtual DbSet<ClientPhoto> ClientPhotoes { get; set; }
        public virtual DbSet<ClientProfile> ClientProfiles { get; set; }
        public virtual DbSet<ClientProfileModule> ClientProfileModules { get; set; }
        public virtual DbSet<Insider> Insiders { get; set; }
        public virtual DbSet<InsiderHeaderPhoto> InsiderHeaderPhotoes { get; set; }
        public virtual DbSet<InsiderPayInfo> InsiderPayInfoes { get; set; }
        public virtual DbSet<InsiderPayStatu> InsiderPayStatus { get; set; }
        public virtual DbSet<InsiderPhoto> InsiderPhotoes { get; set; }
        public virtual DbSet<InsiderProfile> InsiderProfiles { get; set; }
        public virtual DbSet<InsiderProfileModule> InsiderProfileModules { get; set; }
        public virtual DbSet<InsiderSkill> InsiderSkills { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<RequestStatu> RequestStatus { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceOrderItem> ServiceOrderItems { get; set; }
        public virtual DbSet<ServiceRequest> ServiceRequests { get; set; }
        public virtual DbSet<ServiceType> ServiceTypes { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<SkillLevel> SkillLevels { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
