//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskInsider
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public int UserTypeID { get; set; }
        public int ClientID { get; set; }
        public int InsiderID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Insider Insider { get; set; }
    }
}
